# -*- coding: utf-8 -*-
"""daily_sentiment_aggregation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vfw4eXDU0b6CWm7X3YFZb1hT59_iif3f
"""

from google.colab import drive
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import pandas as pd
import kagglehub

drive.mount('/content/drive')

model_path = "/content/drive/Shared drives/comp 576/finbert_model"


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForSequenceClassification.from_pretrained(model_path).to(device)

# Download latest version
path = kagglehub.dataset_download("aaron7sun/stocknews")

print("Path to dataset files:", path)

df_b = pd.read_csv(f"{path}/Combined_News_DJIA.csv", encoding="latin1")
# cols = ["Date", "Label"] + [f"Top{i}" for i in range(1, 26)]
# df_b.columns = cols

df_b

headline_cols = [col for col in df_b.columns if col.startswith("Top")]

def clean_text(x):
    if isinstance(x, bytes):
        return x.decode("latin1", errors="ignore")
    if pd.isna(x):
        return ""
    return str(x)

for col in headline_cols:
    df_b[col] = df_b[col].apply(clean_text)

df_b["headlines"] = df_b[headline_cols].values.tolist()
df_b.head()

def predict_sentiment_list(text_list):
    sentiments = []
    for text in text_list:
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True).to(device)
        with torch.no_grad():
            logits = model(**inputs).logits
        pred = torch.argmax(logits, dim=1).item()
        sentiments.append(pred)
    return sentiments

df_b["sentiments"] = df_b["headlines"].apply(predict_sentiment_list)
df_b[["Date", "sentiments"]].head()

df_b["sentiment_score"] = df_b["sentiments"].apply(lambda x: sum(x) / len(x))

df_b

output_path = "/content/drive/Shared drives/comp 576/daily_sentiment_scores.csv"
df_b[["Date", "sentiment_score"]].to_csv(output_path, index=False)

print("Saved:", output_path)

df_stage2 = df_b[["Date", "sentiment_score", "Label"]].copy()

df_stage2

output_path2 = "/content/drive/Shared drives/comp 576/news_label_daily_sentiment_scores.csv"
df_b[["Date", "sentiment_score", "Label"]].to_csv(output_path2, index=False)