# -*- coding: utf-8 -*-
"""finbert_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7lAhwRSLPxx_GcCJpvgbhN50ocXPFtm
"""

!pip install transformers datasets accelerate -q

!pip install -U transformers

import pandas as pd
from sklearn.model_selection import train_test_split
import kagglehub
from transformers import TrainingArguments, Trainer
import numpy as np
from sklearn.metrics import accuracy_score, f1_score
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Download latest version
path = kagglehub.dataset_download("ankurzing/sentiment-analysis-for-financial-news")
print("Path to dataset files:", path)

df = pd.read_csv(f"{path}/all-data.csv", header=None, encoding="latin1")
df.columns = ["label", "headline"]

print(df.head())
print("Dataset size:", len(df))

label_map = {"negative": 0, "neutral": 1, "positive": 2}
df["label_id"] = df["label"].map(label_map)

# train/val split
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df["label_id"])

model_name = "yiyanghkust/finbert-tone"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3  # positive/neutral/negative
)

train_ds = Dataset.from_pandas(train_df[["headline", "label_id"]])
val_ds   = Dataset.from_pandas(val_df[["headline", "label_id"]])

def tokenize(batch):
    return tokenizer(
        batch["headline"],
        padding="max_length",
        truncation=True,
        max_length=64
    )

train_ds = train_ds.map(tokenize, batched=True)
val_ds   = val_ds.map(tokenize, batched=True)

train_ds = train_ds.rename_column("label_id", "labels")
val_ds   = val_ds.rename_column("label_id", "labels")

train_ds.set_format("torch")
val_ds.set_format("torch")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    acc  = accuracy_score(labels, preds)
    f1   = f1_score(labels, preds, average="weighted")
    return {"accuracy": acc, "f1": f1}

training_args = TrainingArguments(
    output_dir="./finbert_sentiment_model",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()

import numpy as np
from sklearn.metrics import confusion_matrix

pred_output = trainer.predict(val_ds)

y_true = pred_output.label_ids
y_pred = np.argmax(pred_output.predictions, axis=1)

cm = confusion_matrix(y_true, y_pred)
print(cm)

from google.colab import drive
drive.mount('/content/drive')

import os
os.makedirs("/content/drive/Shared drives/comp 576/finbert_model", exist_ok=True)

save_path = "/content/drive/Shared drives/comp 576/finbert_model"

model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("Model saved to:", save_path)